-- ACHADINHOSBR — MIGRAÇÃO V6 (V3: analytics de visualização por oferta/categoria)
-- Execute UMA VEZ no SQL Editor do Supabase, após a migracao-v5.sql.
-- NÃO toca em dados existentes: só CREATE IF NOT EXISTS.
-- Cliques de saída continuam em `clicks` (com offer_id/campaign/placement/device
-- da V5). Esta tabela guarda apenas VISUALIZAÇÕES (sem PII, sem IP).

create extension if not exists pgcrypto;

create table if not exists public.offer_events (
  id bigint generated by default as identity primary key,
  offer_id uuid references public.offers(id) on delete set null,
  tipo text not null
    check (tipo in ('page_view', 'offer_view', 'category_view', 'whatsapp_click', 'social_click')),
  source text,
  campaign text,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists offer_events_offer_idx on public.offer_events(offer_id);
create index if not exists offer_events_tipo_idx on public.offer_events(tipo);
create index if not exists offer_events_created_at_idx on public.offer_events(created_at desc);

alter table public.offer_events enable row level security;

-- Insert público (qualquer visitante registra visualização).
drop policy if exists "Registrar evento público" on public.offer_events;
create policy "Registrar evento público"
on public.offer_events for insert
to anon, authenticated
with check (true);

-- Leitura só admin.
drop policy if exists "Admin lê offer_events" on public.offer_events;
create policy "Admin lê offer_events"
on public.offer_events for select
to authenticated
using (public.is_admin());
