-- ACHADINHOSBR — MIGRAÇÃO V4 (marketplaces + score + aprovação + whatsapp)
-- Execute UMA VEZ no SQL Editor do Supabase, na ordem do arquivo.
-- NÃO toca nas tabelas legadas: produtos, cliques, anuncios, historico_precos, admin_users.
-- Cria o modelo V4 em inglês: products, clicks, whatsapp_queue, whatsapp_logs.
-- RLS: leitura pública só de products aprovados; escrita só admin; clicks com insert público.

-- ===== 0. Extensão (idempotente) =====
create extension if not exists pgcrypto;

-- ===== 1. PRODUCTS (V4) =====
-- Guarda título, imagem, preço, preço anterior, desconto, avaliações, vendas,
-- URL (não-afiliada) e affiliate_url (SOMENTE link oficial de afiliado).
-- ML: nunca transformar link comum em afiliado por método não oficial.
-- Shopee: affiliate_url vem da Shopee Affiliate Open API (server-only).
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  image text not null,
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= 0),
  discount integer check (discount is null or (discount >= 0 and discount <= 90)),
  rating numeric(2,1) not null default 0 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  sold integer not null default 0 check (sold >= 0),
  url text not null,
  affiliate_url text,
  marketplace text not null default 'mercadolivre'
    check (marketplace in ('mercadolivre', 'shopee')),
  commission numeric(12,2) check (commission is null or commission >= 0),
  commission_rate numeric(5,2) check (commission_rate is null or (commission_rate >= 0 and commission_rate <= 100)),
  score integer not null default 0 check (score >= 0 and score <= 100),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  external_id text,
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_approved_requires_affiliate
    check (status != 'approved' or affiliate_url is not null)
);

create index if not exists products_status_idx on public.products(status);
create index if not exists products_marketplace_idx on public.products(marketplace);
create index if not exists products_score_idx on public.products(score desc);
create index if not exists products_created_at_idx on public.products(created_at desc);
create index if not exists products_marketplace_external_idx
  on public.products(marketplace, external_id);

-- updated_at automático
create or replace function public.touch_products_updated_at()
returns trigger language plpgsql set search_path = public
as $$
begin
  NEW.updated_at = now();
  return NEW;
end $$;

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.touch_products_updated_at();

alter table public.products enable row level security;

-- Público (anon + autenticado): lê SOMENTE aprovados. Pending/rejected ficam invisíveis.
drop policy if exists "Products aprovados são públicos" on public.products;
create policy "Products aprovados são públicos"
on public.products for select
to anon, authenticated
using (status = 'approved');

-- Admin (admin_users): leitura/escrita total.
drop policy if exists "Admin lê products" on public.products;
create policy "Admin lê products"
on public.products for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin insere products" on public.products;
create policy "Admin insere products"
on public.products for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin atualiza products" on public.products;
create policy "Admin atualiza products"
on public.products for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin exclui products" on public.products;
create policy "Admin exclui products"
on public.products for delete
to authenticated
using (public.is_admin());

-- ===== 2. CLICKS (V4) =====
-- Rastreamento da rota /ver/[id]: produto, marketplace, data/hora, referer, user-agent.
-- Não guarda IP original (só hash) — mesmo padrão da tabela legada cliques.
create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  marketplace text,
  created_at timestamptz not null default now(),
  referer text,
  user_agent text,
  origin text,
  session_id text,
  ip_hash text
);

create index if not exists clicks_product_id_idx on public.clicks(product_id);
create index if not exists clicks_created_at_idx on public.clicks(created_at);
create index if not exists clicks_marketplace_idx on public.clicks(marketplace);

alter table public.clicks enable row level security;

-- Insert público (anon + autenticado): qualquer visitante pode registrar clique.
drop policy if exists "Registrar click público" on public.clicks;
create policy "Registrar click público"
on public.clicks for insert
to anon, authenticated
with check (true);

-- Leitura só admin.
drop policy if exists "Admin lê clicks" on public.clicks;
create policy "Admin lê clicks"
on public.clicks for select
to authenticated
using (public.is_admin());

-- ===== 3. WHATSAPP_QUEUE (V4) =====
-- Fila de ofertas para WhatsApp. SEM automação não oficial (risco de bloqueio).
-- Envio somente via API oficial (WhatsApp Business / Cloud API) em server-only.
create table if not exists public.whatsapp_queue (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  status text not null default 'queued'
    check (status in ('queued', 'sent', 'failed', 'cancelled')),
  message text,
  scheduled_for timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists whatsapp_queue_status_idx on public.whatsapp_queue(status);
create index if not exists whatsapp_queue_created_at_idx on public.whatsapp_queue(created_at desc);
create index if not exists whatsapp_queue_product_idx on public.whatsapp_queue(product_id);

alter table public.whatsapp_queue enable row level security;

drop policy if exists "Admin gerencia whatsapp_queue" on public.whatsapp_queue;
create policy "Admin gerencia whatsapp_queue"
on public.whatsapp_queue for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ===== 4. WHATSAPP_LOGS (V4) =====
create table if not exists public.whatsapp_logs (
  id bigint generated by default as identity primary key,
  queue_id uuid references public.whatsapp_queue(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  action text not null,
  result text,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists whatsapp_logs_queue_idx on public.whatsapp_logs(queue_id);
create index if not exists whatsapp_logs_product_idx on public.whatsapp_logs(product_id);
create index if not exists whatsapp_logs_created_at_idx on public.whatsapp_logs(created_at desc);

alter table public.whatsapp_logs enable row level security;

drop policy if exists "Admin lê whatsapp_logs" on public.whatsapp_logs;
create policy "Admin lê whatsapp_logs"
on public.whatsapp_logs for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin insere whatsapp_logs" on public.whatsapp_logs;
create policy "Admin insere whatsapp_logs"
on public.whatsapp_logs for insert
to authenticated
with check (public.is_admin());

-- ===== 5. VIEW de apoio ao painel V4 =====
drop view if exists public.v4_product_stats;
create view public.v4_product_stats
with (security_invoker = true)
as
select
  p.id,
  p.title,
  p.marketplace,
  p.status,
  p.score,
  p.price,
  count(c.id)::bigint as clicks
from public.products p
left join public.clicks c on c.product_id = p.id
group by p.id, p.title, p.marketplace, p.status, p.score, p.price
order by p.score desc;
