-- ACHADINHOSBR — MIGRAÇÃO V3 (banco existente v1/v2 → v3 seguro)
-- Execute UMA VEZ no SQL Editor do Supabase, na ordem do arquivo.
-- Não apaga produtos nem cliques. Desativa (ativo=false) e limpa o link
-- apenas das linhas cujo link de afiliado é genérico/inválido — o RETURNING
-- no passo 4 mostra exatamente quais foram afetadas para revisão.

-- ===== 1. Tabela de administradores + função is_admin() (FASE 1) =====
create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Usuário lê próprio registro admin" on public.admin_users;
create policy "Usuário lê próprio registro admin"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = auth.uid()) $$;

-- ===== 2. Novas colunas de produto (FASE 2) =====
alter table public.produtos add column if not exists descricao text;
alter table public.produtos add column if not exists link_produto text;
alter table public.produtos add column if not exists ml_product_id text;
alter table public.produtos add column if not exists prioridade integer not null default 0;
alter table public.produtos add column if not exists preco_atualizado_em timestamptz not null default now();
alter table public.produtos add column if not exists verificado_em timestamptz;

update public.produtos set verificado_em = created_at where verificado_em is null;

-- Link passa a ser opcional no banco; a publicação exige link (constraint abaixo).
alter table public.produtos alter column link_afiliado drop not null;

-- ===== 3. Novas colunas de clique (FASE 4+12) =====
alter table public.cliques add column if not exists origem text;
alter table public.cliques add column if not exists sessao_id text;
alter table public.cliques add column if not exists ip_hash text;
create index if not exists cliques_origem_idx on public.cliques(origem);

-- ===== 3b. Histórico de preços (base futura p/ alerta de preço) =====
create table if not exists public.historico_precos (
  id bigint generated by default as identity primary key,
  produto_id uuid not null references public.produtos(id) on delete cascade,
  preco numeric(12,2) not null,
  preco_antigo numeric(12,2),
  criado_em timestamptz not null default now()
);
create index if not exists historico_produto_id_idx on public.historico_precos(produto_id);
alter table public.historico_precos enable row level security;
drop policy if exists "Admin lê histórico" on public.historico_precos;
create policy "Admin lê histórico"
on public.historico_precos for select
to authenticated
using (public.is_admin());

create or replace function public.registrar_historico_preco()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if (TG_OP = 'INSERT') or (OLD.preco is distinct from NEW.preco) or (OLD.preco_antigo is distinct from NEW.preco_antigo) then
    insert into public.historico_precos (produto_id, preco, preco_antigo)
    values (NEW.id, NEW.preco, NEW.preco_antigo);
  end if;
  return NEW;
end $$;
drop trigger if exists trg_historico_preco on public.produtos;
create trigger trg_historico_preco
after insert or update of preco, preco_antigo on public.produtos
for each row execute function public.registrar_historico_preco();

-- ===== 4. Seeds genéricos viram exemplo inativo (FASE 13) =====
-- Mostra as linhas afetadas para conferência. Depois disso o admin
-- substitui pelos produtos reais no painel.
update public.produtos
set ativo = false, link_afiliado = null,
    descricao = coalesce(descricao, 'EXEMPLO — substitua por produto real com link de afiliado específico.')
where link_afiliado is not null and not (
  link_afiliado ~* '^https://([^/]+\.)?(mercadolivre\.com(\.br)?|mlivre\.[a-z.]+)/.+'
  and length(link_afiliado) > 30
  and link_afiliado !~* '/(cart|carrinho|checkout|search)'
  and link_afiliado !~* 'busca'
  and link_afiliado !~* '^https?://([^/]+\.)?mercadolivre\.com(\.br)?/?(\?.*)?$'
)
returning id, slug, nome, ativo;

-- ===== 5. Constraints de validade do link (FASE 2) =====
alter table public.produtos drop constraint if exists produto_ativo_exige_link;
alter table public.produtos add constraint produto_ativo_exige_link
check (ativo = false or link_afiliado is not null);

alter table public.produtos drop constraint if exists link_afiliado_valido;
alter table public.produtos add constraint link_afiliado_valido
check (
  link_afiliado is null or (
    link_afiliado ~* '^https://([^/]+\.)?(mercadolivre\.com(\.br)?|mlivre\.[a-z.]+)/.+'
    and length(link_afiliado) > 30
    and link_afiliado !~* '/(cart|carrinho|checkout|search)'
    and link_afiliado !~* 'busca'
    and link_afiliado !~* '^https?://([^/]+\.)?mercadolivre\.com(\.br)?/?(\?.*)?$'
  )
);

-- ===== 6. Policies baseadas em admin_users (FASE 1) =====
-- Remove as policies amplas/por e-mail anteriores (nomes das v1 e v2).
drop policy if exists "Admin lê produtos" on public.produtos;
drop policy if exists "Admin insere produtos" on public.produtos;
drop policy if exists "Admin atualiza produtos" on public.produtos;
drop policy if exists "Admin exclui produtos" on public.produtos;
drop policy if exists "Admin lê cliques" on public.cliques;

create policy "Admin lê produtos"
on public.produtos for select to authenticated using (public.is_admin());

create policy "Admin insere produtos"
on public.produtos for insert to authenticated with check (public.is_admin());

create policy "Admin atualiza produtos"
on public.produtos for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "Admin exclui produtos"
on public.produtos for delete to authenticated using (public.is_admin());

create policy "Admin lê cliques"
on public.cliques for select to authenticated using (public.is_admin());

-- (As policies públicas "Produtos ativos são públicos" e
-- "Registrar clique público" são mantidas como estão.)

-- ===== 7. View do dashboard com categoria (FASE 5) =====
create or replace view public.produto_cliques
with (security_invoker = true)
as
select
  p.id, p.nome, p.categoria, p.categoria_slug,
  count(c.id)::bigint as cliques
from public.produtos p
left join public.cliques c on c.produto_id = p.id
group by p.id, p.nome, p.categoria, p.categoria_slug
order by cliques desc;

-- ===== 8. Bootstrap do administrador atual =====
-- Cadastra como admin o usuário já usado no painel. Para adicionar
-- outros admins, repita com o e-mail correspondente.
insert into public.admin_users (user_id, role)
select id, 'admin' from auth.users where email = 'luiz988061337@gmail.com'
on conflict (user_id) do nothing;
