-- ACHADINHOSBR V3 (seguro)
-- Instalação nova: execute este arquivo no SQL Editor do Supabase.
-- Banco existente (v1/v2): execute supabase/migracao-v3.sql em vez deste.

create extension if not exists pgcrypto;

-- ============ TABELA DE ADMINISTRADORES (FASE 1) ============
-- Somente usuários listados aqui passam em is_admin().
-- Gerencie por SQL (service role / dashboard). Não há escrita via anon key.
create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique not null references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Usuário lê próprio registro admin" on public.admin_users;
create policy "Usuário lê próprio registro admin"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = auth.uid()) $$;

-- ============ PRODUTOS (FASES 1+2) ============
create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  nome text not null,
  descricao text,
  imagem text not null,
  preco numeric(12,2) not null,
  preco_antigo numeric(12,2),
  desconto integer,
  categoria text not null,
  categoria_slug text not null,
  avaliacao numeric(2,1) default 5,
  avaliacoes integer default 0,
  link_produto text,
  link_afiliado text,
  ml_product_id text,
  ativo boolean default true,
  destaque boolean default false,
  prioridade integer not null default 0,
  preco_atualizado_em timestamptz not null default now(),
  verificado_em timestamptz,
  created_at timestamptz not null default now(),
  constraint produto_ativo_exige_link check (ativo = false or link_afiliado is not null),
  constraint link_afiliado_valido check (
    link_afiliado is null or (
      (
        link_afiliado ~* '^https://([^/]+\.)?(mercadolivre\.com(\.br)?|mlivre\.[a-z.]+)/.+'
        and length(link_afiliado) > 30
        and link_afiliado !~* '/(cart|carrinho|checkout|search)'
        and link_afiliado !~* 'busca'
        and link_afiliado !~* '^https?://([^/]+\.)?mercadolivre\.com(\.br)?/?(\?.*)?$'
      )
      or link_afiliado ~* '^https://meli\.la/[A-Za-z0-9]{3,}/*(\?.*)?$'
    )
  )
);

-- ============ CLIQUES (FASES 1+4+12) ============
-- ip: coluna legada, não é mais preenchida (ver ip_hash).
-- Não armazene SERVICE_ROLE nem dados pessoais além do necessário.
create table if not exists public.cliques (
  id bigint generated by default as identity primary key,
  produto_id uuid not null references public.produtos(id) on delete cascade,
  criado_em timestamptz not null default now(),
  pagina_origem text,
  origem text,
  sessao_id text,
  user_agent text,
  ip text,
  ip_hash text
);

create index if not exists cliques_produto_id_idx on public.cliques(produto_id);
create index if not exists cliques_criado_em_idx on public.cliques(criado_em);
create index if not exists cliques_origem_idx on public.cliques(origem);

-- ============ HISTÓRICO DE PREÇOS (base para alerta de preço) ============
-- Só guarda preço/preço-antigo/data. Sem integração fictícia.
create table if not exists public.historico_precos (
  id bigint generated by default as identity primary key,
  produto_id uuid not null references public.produtos(id) on delete cascade,
  preco numeric(12,2) not null,
  preco_antigo numeric(12,2),
  criado_em timestamptz not null default now()
);

create index if not exists historico_produto_id_idx on public.historico_precos(produto_id);

alter table public.historico_precos enable row level security;

drop policy if exists "Admin lê histórico" on public.historico_precos;
create policy "Admin lê histórico"
on public.historico_precos for select
to authenticated
using (public.is_admin());

create or replace function public.registrar_historico_preco()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if (TG_OP = 'INSERT') or (OLD.preco is distinct from NEW.preco) or (OLD.preco_antigo is distinct from NEW.preco_antigo) then
    insert into public.historico_precos (produto_id, preco, preco_antigo)
    values (NEW.id, NEW.preco, NEW.preco_antigo);
  end if;
  return NEW;
end $$;

drop trigger if exists trg_historico_preco on public.produtos;
create trigger trg_historico_preco
after insert or update of preco, preco_antigo on public.produtos
for each row execute function public.registrar_historico_preco();

-- ============ CENTRAL DE ANÚNCIOS ============
-- Histórico das peças geradas (produto, formato, modelo, campanha, texto).
-- Cliques por criativo via cliques.anuncio_id (comparar A/B por dados reais).
create table if not exists public.anuncios (
  id uuid primary key default gen_random_uuid(),
  produto_id uuid not null references public.produtos(id) on delete cascade,
  formato text not null,
  modelo text not null,
  campanha text,
  texto text,
  admin_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists anuncios_produto_id_idx on public.anuncios(produto_id);
create index if not exists anuncios_created_at_idx on public.anuncios(created_at);

alter table public.anuncios enable row level security;

drop policy if exists "Admin gerencia anuncios" on public.anuncios;
create policy "Admin gerencia anuncios"
on public.anuncios for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

alter table public.cliques add column if not exists anuncio_id uuid references public.anuncios(id) on delete set null;
create index if not exists cliques_anuncio_id_idx on public.cliques(anuncio_id);

alter table public.produtos enable row level security;
alter table public.cliques enable row level security;

-- ---- Produtos: público vê somente ativos ----
drop policy if exists "Produtos ativos são públicos" on public.produtos;
create policy "Produtos ativos são públicos"
on public.produtos for select
to anon, authenticated
using (ativo = true);

-- ---- Produtos: somente administradores (tabela admin_users) ----
drop policy if exists "Admin lê produtos" on public.produtos;
create policy "Admin lê produtos"
on public.produtos for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin insere produtos" on public.produtos;
create policy "Admin insere produtos"
on public.produtos for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin atualiza produtos" on public.produtos;
create policy "Admin atualiza produtos"
on public.produtos for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin exclui produtos" on public.produtos;
create policy "Admin exclui produtos"
on public.produtos for delete
to authenticated
using (public.is_admin());

-- ---- Cliques: registro público, leitura só admin ----
drop policy if exists "Registrar clique público" on public.cliques;
create policy "Registrar clique público"
on public.cliques for insert
to anon, authenticated
with check (true);

drop policy if exists "Admin lê cliques" on public.cliques;
create policy "Admin lê cliques"
on public.cliques for select
to authenticated
using (public.is_admin());

-- ---- Dashboard ----
create or replace view public.produto_cliques
with (security_invoker = true)
as
select
  p.id,
  p.nome,
  p.categoria,
  p.categoria_slug,
  count(c.id)::bigint as cliques
from public.produtos p
left join public.cliques c on c.produto_id = p.id
group by p.id, p.nome, p.categoria, p.categoria_slug
order by cliques desc;

-- ============ SEEDS DE EXEMPLO (FASE 13) ============
-- PRODUTOS DE EXEMPLO, INATIVOS e SEM link: substitua por produtos reais
-- com link de afiliado específico no painel /admin antes de divulgar.
insert into public.produtos
(slug,nome,descricao,imagem,preco,preco_antigo,desconto,categoria,categoria_slug,avaliacao,avaliacoes,link_afiliado,ativo,destaque)
values
('air-fryer-5l','Air Fryer 5L Digital','EXEMPLO — substitua por produto real.','https://images.unsplash.com/photo-1585515320310-259814833e62?w=900',299.90,399.90,25,'Cozinha','cozinha',4.8,1250,null,false,false),
('fone-bluetooth','Fone Bluetooth Sem Fio','EXEMPLO — substitua por produto real.','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900',89.90,129.90,31,'Eletrônicos','eletronicos',4.7,890,null,false,false),
('furadeira-eletrica','Furadeira e Parafusadeira 12V','EXEMPLO — substitua por produto real.','https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900',159.90,219.90,27,'Ferramentas','ferramentas',4.9,620,null,false,false)
on conflict (slug) do nothing;
