-- ACHADINHOSBR V2
-- Cole este arquivo no SQL Editor do Supabase e execute.

create extension if not exists pgcrypto;

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  nome text not null,
  imagem text not null,
  preco numeric(12,2) not null,
  preco_antigo numeric(12,2),
  desconto integer,
  categoria text not null,
  categoria_slug text not null,
  avaliacao numeric(2,1) default 5,
  avaliacoes integer default 0,
  destaque boolean default false,
  link_afiliado text not null,
  ativo boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cliques (
  id bigint generated by default as identity primary key,
  produto_id uuid not null references public.produtos(id) on delete cascade,
  criado_em timestamptz not null default now(),
  pagina_origem text,
  user_agent text,
  ip text
);

create index if not exists cliques_produto_id_idx on public.cliques(produto_id);
create index if not exists cliques_criado_em_idx on public.cliques(criado_em);

alter table public.produtos enable row level security;
alter table public.cliques enable row level security;

-- Produtos: visitantes só podem ler produtos ativos.
drop policy if exists "Produtos ativos são públicos" on public.produtos;
create policy "Produtos ativos são públicos"
on public.produtos for select
to anon, authenticated
using (ativo = true);

-- Administrador autenticado pode ler todos os produtos.
drop policy if exists "Admin lê produtos" on public.produtos;
create policy "Admin lê produtos"
on public.produtos for select
to authenticated
using (true);

-- Para este projeto, qualquer usuário autenticado pode administrar produtos.
-- Se quiser limitar a um único e-mail/role, altere esta policy depois.
drop policy if exists "Admin insere produtos" on public.produtos;
create policy "Admin insere produtos"
on public.produtos for insert
to authenticated
with check (true);

drop policy if exists "Admin atualiza produtos" on public.produtos;
create policy "Admin atualiza produtos"
on public.produtos for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admin exclui produtos" on public.produtos;
create policy "Admin exclui produtos"
on public.produtos for delete
to authenticated
using (true);

-- Registro público de clique: não libera leitura.
drop policy if exists "Registrar clique público" on public.cliques;
create policy "Registrar clique público"
on public.cliques for insert
to anon, authenticated
with check (true);

-- Apenas usuários autenticados podem consultar cliques.
drop policy if exists "Admin lê cliques" on public.cliques;
create policy "Admin lê cliques"
on public.cliques for select
to authenticated
using (true);

-- View para o dashboard.
create or replace view public.produto_cliques
with (security_invoker = true)
as
select
  p.id,
  p.nome,
  count(c.id)::bigint as cliques
from public.produtos p
left join public.cliques c on c.produto_id = p.id
group by p.id, p.nome
order by cliques desc;

-- Dados de exemplo.
insert into public.produtos
(slug,nome,imagem,preco,preco_antigo,desconto,categoria,categoria_slug,avaliacao,avaliacoes,destaque,link_afiliado,ativo)
values
('air-fryer-5l','Air Fryer 5L Digital','https://images.unsplash.com/photo-1585515320310-259814833e62?w=900',299.90,399.90,25,'Cozinha','cozinha',4.8,1250,true,'https://mercadolivre.com.br/',true),
('fone-bluetooth','Fone Bluetooth Sem Fio','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900',89.90,129.90,31,'Eletrônicos','eletronicos',4.7,890,true,'https://mercadolivre.com.br/',true),
('furadeira-eletrica','Furadeira e Parafusadeira 12V','https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900',159.90,219.90,27,'Ferramentas','ferramentas',4.9,620,true,'https://mercadolivre.com.br/',true)
on conflict (slug) do nothing;
